### ISSUE TITLE
Error: Failed to resolve: com.afollestad:material-dialogs:0.7.5.1 when compiling this app

### ISSUE THREAD

**Issue by BadihBarakat** [adrianblp/Noraoke#2]
Hi,
I have downloaded this app and it is showing:
`Error:(28, 13) Failed to resolve: com.afollestad:material-dialogs:0.7.5.1`

I added the below in build.gradle of the app module:

`repositories {
    jcenter()
    maven { url "https://jitpack.io" }
    }`

It didn't solve the problem.
Can you please advise me in this regard?
Thanks,

**Comment by adrianblancode** [comment]
So the problem seems to be that repository has disappeared from jcenter, and has moved to `com.afollestad.material-dialogs:code`. And that seems to require Android Studio 3.0 along with a couple other things to make the code work with what has happened in Android for the past three years. 

https://github.com/afollestad/material-dialogs/issues/1335

This app was basically a demo prototype designed to be shown just for one presentation, eg the sync server has been taken down also, so there's not much to expect in the first place. The pictures make it look much better, so there's not much value in spending time to fix it :)

**Comment by adrianblancode** [comment]
If there's a need, the APK can be found here: https://github.com/adrianblp/adrianblp.github.io/raw/56c10eebd1b01cafb219c965c208b89d8c9ad18f/_site/content/Noraoke.apk
