### ISSUE TITLE
Error:Unsupported method: BaseConfig.getApplicationIdSuffix(). The version of Gradle you connect to does not support that method. To resolve the problem you can change/upgrade the target version of Gradle you connect to. Alternatively, you can ignore this exception and read other information from the model.

### ISSUE THREAD

**Issue by laughingstocK** [adrianblp/Noraoke#3]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "co.adrianblan.noraoke"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:design:22.2.0'
    compile 'com.jpardogo.materialtabstrip:library:1.0.9'
    compile 'com.melnykov:floatingactionbutton:1.2.0'
    compile 'com.github.ksoichiro:android-observablescrollview:1.5.0'
    compile "org.java-websocket:Java-WebSocket:1.3.0"
    compile 'com.afollestad:material-dialogs:0.7.5.1'
}

**Comment by adrianblancode** [comment]
This seems to be due to that the build tools version is too low for Android Studio 3, or something like that. 

Currently there is no plans to develop this demo to support modern build setups, as that would take a lot of work for little payoff. If you want the unsigned APK, it can be found here: https://github.com/adrianblp/adrianblp.github.io/raw/56c10eebd1b01cafb219c965c208b89d8c9ad18f/_site/content/Noraoke.apk

**Comment by laughingstocK** [comment]
thanks
